### ISSUE TITLE
Optimize data storage for better performance

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#11]
Received this comment: 
>I think the structure of the connections dictionary needs to be reconsidered. I switched a few parts of the implementation to be array based and use slicing instead of loops.
My latest experiments have a multiprocessed, 1440 timestep, run executing in just under a minute on my laptop. The serial version runs in about 1m45s.

**Comment by jameshalgren** [comment]
@groutr Thanks for this issue. When it works we'd love a pull request.

**Comment by groutr** [comment]
This was experimented with using the single reach code.
The main ideas here are:
1. Separate the graph from the data. This simplified a many of the graph operations
2. Keep the data as a single numpy array, sorted by node id. Keeping things together in memory helped a lot IIRC. Using numpy types rather than python objects also reduced memory consumption quite a bit. The sorting was important because we used a binary search to generate masks for subsets of the graph.
3. Use a numpy array to track flowdepth. The index corresponded to the index of the sorted data array.

By using numpy arrays, slicing could be used to eliminate almost all of the looping in the single reach code.

**Comment by jameshalgren** [comment]
Closed with #110 (see issue #11)
