### ISSUE TITLE
Add logging to replace "debuglevel" and "verbose" in v02 code

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#144]
v02 contains no debugging or verbose code.

**Comment by jameshalgren** [comment]
This issue was originally a request for debuglevel and verbose printing in the v02 code. We've changed it to a request for logging integration. The concern, generally speaking, is that we cannot print from the cython code (due to GIL). Also, logging in the nhd_*.py files (instead of a bunch of debug print statements) provides much greater flexibility and performance. 

We can reference [this tutorial for a start](https://docs.python.org/3/howto/logging.html#logging-flow)

The concept is to create a very high level layer to report what is going on and avoid branching and print statements in the to the performance critical portions of the code. That high-level layer could report on the objects that get returned at various points in the code.

For example, make a call to nhd_network for extracting the network. Then, instead of putting print statements in extract_network, after the call is made print (to the log) the size and dimensions of the network that is returned.
@groutr

**Comment by jhrehanoaa** [comment]
This PR contains changes to the print statements used for verbose and debuglevel. Command line verbose and debuglevel input still determine the outputs. The new changes allow for a timestamped log level for each debuglevel. The order of output log levels are as following: -verbose -> INFO, -debuglevel 1 -> debug, -debuglevel 2 -> warning, and -debuglevel 3 -> critical. Essentially the same output and reasoning as before, but with additional writing to a log file and timestamping. New command line argument for overwriting versus appending to the log output file as well as selecting a location/name for the output file.

**Comment by groutr** [comment]
What happens when a user specifies both -verbose and -debuglevel 1? Which flag takes precedence?
It might make more sense to have just one flag. One pattern that many projects adapt is that of passing verbose multiple times.
For example, assume the default level is WARNING (as the logging module assumes). Then `-v` would map to INFO, `-v -v` maps to DEBUG.

**Comment by jameshalgren** [comment]
To get started with this may be as simple as including the following in __main__.py:

```
import logging
import sys

logging.basicConfig(
    level=logging.DEBUG,
    format='%(levelname)7s: %(message)s',
    stream=sys.stderr,
)
LOG = logging.getLogger('')
```
and then wherever we need to output to the log, using: 
```
LOG.info('inner starting')
```
The way this is configured, the message is printing to stderr, which can be easily redirected to a file at the command line. 
The example quoted here is https://pymotw.com/3/asyncio/debugging.html, for reference.

**Comment by JurgenZach-NOAA** [comment]
While the links are still potentially useful, logging has been addressed in multiple PRs since, most recently 786 and 796, and any issue should be based upon the recent state of the art.
