### ISSUE TITLE
Write out Last Obs file

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#437]
During long-term looping scenarios, we need to be able to write out and save the last observation values based on the current values, time since last obs, and when the last obs file first occurs. Hopefully, this can be saved out and read using the same functions already in place in mc_reach, but may require some slight modifications to restart from the new referenced location. 

This should contain: 
- Last obs values array
- Last obs time since observation array
- Last obs start timeslice

**Comment by awlostowski-noaa** [comment]
Here is the xarray dataset created when a LastObs file is opened in `nhd_io.build_last_obs_df`
```
<xarray.Dataset>
Dimensions:            (feature_id: 68507, stationIdInd: 145, timeInd: 480)
Dimensions without coordinates: feature_id, stationIdInd, timeInd
Data variables:
    stationId          (stationIdInd) |S15 ...
    time               (stationIdInd, timeInd) |S19 ...
    discharge          (stationIdInd, timeInd) float32 ...
    model_discharge    (stationIdInd, timeInd) float32 ...
    discharge_quality  (stationIdInd, timeInd) int16 ...
    nudge              (feature_id) float32 ...
Attributes:
    modelTimeAtOutput:  2018-09-17_00:00:00
```
The `time`, `discharge`, model_discharge`, and `discharge_quality`, and `discharge_quality` variables all have the same dimensions: `stationIdInd` x `timeInd`, where `stationIdInd` is the number of gage locations and `timeInd` is the number of timestamps reported. 

LastObs files report `timeInd` number of retrospective observation timestamps prior to the `modelTimeAtOutput` attribute. The reason for reporting a retrospective timeseries of observation is to allow for bias corrections in the DA scheme. Because our DA scheme does not yet use bias corrections, I think we can get the ball rolling  by just reporting variables at a single timestamp- the most recent observation time prior to `modelTimeAtOutput`. In other words, the LastObs files created by t-route will have dimension `timeInd: 1`

**Comment by awlostowski-noaa** [comment]
A function that writes LastObs files will need access to the following pieces of data

- The timestamp at which the LastObs file is to be created - i.e. `modelTimeAtOutput`
- The time and magnitude of the most recent observation at or prior to `modelTimeAtOutput`
- The nudge value at all gage locations (assume zero elsewhere?) at `modelTimeAtOutput`
- Model discharge at `modelTimeAtOutput`

If we are not doing so already, we will need to hold dataframes or arrays of nudge values and observations (not interpolated) in memory so we can write LastObs files as part of the output processing routine - after the simulation has been completed.

**Comment by awlostowski-noaa** [comment]
Minimum viable product, here. Write out a LastObs dataframe at the end of each loop simulation.

**Comment by jhrehanoaa** [comment]
I have the model returning .nc files and reading .nc files. I have added modelTimeAtOutput to the df when the lastobs is written out as well.

**Comment by jhrehanoaa** [comment]
We have the time since lastobs and the discharge currently. What values would you like in place of nudging?
